### ISSUE TITLE
Please completely remove 657875738464 from code we are having all sorts of logical and emotional set backs cause of the same

### ISSUE THREAD

**Issue by MyvinB** [micgogi/micgogi_algo#1]

**Comment by micgogi** [comment]
I can't remove

**Comment by micgogi** [comment]
cz it's a core functionality of my algorithm. @MyvinB

**Comment by micgogi** [comment]
cz it's a heart of my algorithm

**Comment by MyvinB** [comment]
I hope you are familiar with the concept of loose coupling the dependency 65..64 is not stable and requires revision. I am pretty sure with the coming improvements new algorithms can be developed and a new dependency can be injected into your code. After all keeping dependencies that have depreciated is not fruitful even though its the heart of your algorithm.

**Comment by micgogi** [comment]
yeah, i'll try to remove. It will take time.
